
require 'colorize'
require 'pry'
require_relative 'main'
require_relative 'game'
require_relative 'board'
require_relative 'white_team'
require_relative 'black_team'
require_relative 'coordinate'
require_relative 'piece'
require_relative 'piece_subclasses/pawn'
require_relative 'piece_subclasses/empty_space'
require_relative 'piece_subclasses/rook'
require_relative 'piece_subclasses/knight'
require_relative 'piece_subclasses/bishop'
require_relative 'piece_subclasses/queen'
require_relative 'piece_subclasses/king'
